version: '3.8'
services:
  insurance-api:
    image: insurance:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insurance-api
    restart: always
    ports:
      - '8080:8080'
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  rabbitmq_data: