server:
    servlet:
        context-path: /api

springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html

management:
    endpoints:
        web:
            exposure:
                include: "*"

spring:
    profiles:
        active: dev
    datasource:
        url: jdbc:h2:mem:insurance_db
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
    h2:
        console:
            enabled: true
    rabbitmq:
        host: rabbitmq
        port: 5672
        username: guest
        password: guest

gateway:
    catalog-service:
        url: https://e13286f8-d609-4189-ab16-c70bde15bf9d.mock.pstmn.io

rabbitmq:
    exchange: insurance.policy.exchange
    routingkey:
        insurance-policy-create: policy.routingkey
        insurance-quote-received: quote.routingkey
    queue:
        insurance-policy-create: insurance-policy-create
        insurance-quote-received: insurance-quote-received
        insurance-policy-create-dlq: insurance-policy-create-dlq
    ttl: 604800000  # 7 dias em milissegundos
    max-redeliveries: 3

